name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Move .env
        run: cp .env.production .env

      - name: Modify .env
        run: |
          echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" > .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --production

      - name: Move files
        run: cp package.json build/package.json && cp .env build/.env && cp -R nginx build/nginx

      - name: Deploy artifacts
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: 'build/*'
          target: /var/www/html/

      - name: Copy Nginx configuration
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: 'nginx/jojojuju9.com'
          target: '/etc/nginx/sites-available/jojojuju9.com'

      - name: Enable Nginx site
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo ln -sf /etc/nginx/sites-available/jojojuju9.com /etc/nginx/sites-enabled/
            sudo systemctl reload nginx

      - name: Install packages in production and restart app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /var/www/html && npm install --omit=dev
            cd /var/www/html && node ace migration:run -f -s
            pm2 start ecosystem.config.js
